// Mocks generated by Mockito 5.3.2 from annotations
// in flutter_state/data/repository/todo_api_repo.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_state/data/dataprovider/todo_api.dart' as _i3;
import 'package:flutter_state/data/model/todo_model.dart' as _i5;
import 'package:flutter_state/data/repository/todo_api_repo.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TodoApiRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoApiRepository extends _i1.Mock implements _i2.TodoApiRepository {
  @override
  set todoApi(_i3.TodoApi? _todoApi) => super.noSuchMethod(
        Invocation.setter(
          #todoApi,
          _todoApi,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<List<_i5.Todo?>?> getToDoList() => (super.noSuchMethod(
        Invocation.method(
          #getToDoList,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Todo?>?>.value(),
        returnValueForMissingStub: _i4.Future<List<_i5.Todo?>?>.value(),
      ) as _i4.Future<List<_i5.Todo?>?>);
}
